### ISSUE TITLE
Notification clips off

### ISSUE THREAD

**Issue by mario0318** [jd1378/otphelper#100]
The notification window sometimes gets cut off when another notification comes in right after Copy SMS sends its detected notification. I believe it has to do with the two button options to Ignore App and Ignore Tag. It's really not that big an issue as I have yet to use those options in particular at all (if they can be set by user to be hidden, that would be ideal for most, I believe) except for the fact that the notifications are set not set to be Silent or minimized, and it just seems to be more of an esthetic issue regarding the typeface or font size as programmed. Here are a couple of images for this issue:

**Without a notification having followed CopySMS:**
![Screenshot_20240605-100435](https://github.com/jd1378/otphelper/assets/25380627/1eaaf406-3d16-45a1-b4b9-d9a9114b8078)

**With notification placed above CopySMS:**
![Screenshot_20240605-100525](https://github.com/jd1378/otphelper/assets/25380627/9a3deb34-0b4a-42cd-9071-f42c863e09b8)

This is by no means an urgent issue to resolve, but since the app throws two notifications, one for the detected text parsed and the other to allow for Copy/Ignore, the notification window almost always gets truncated to the point of cutting off the numbers. Can sometimes require a second take to confirm the numbers are what they are.

Thank you for taking the time to develop this great lil program. It truly makes things easier and should be something included in operating systems and shells all over.

**Comment by jd1378** [comment]
Hi
thanks for reporting this issue
actually this issue is not present on any of my phones or emulators
and this issue is probably not because of the two buttons, the buttons are android's default way of interacting with notifications

have you changed the display font size or ui size in the android settings by any chance ? 

also may I know the version of your android, so maybe I can install that version on emulator and reproduce ? also please tell me your screen size or phone model if you may

thank you

**Comment by mario0318** [comment]
I'm on Android 11, on a Motorola G Power. I haven't changed any display ekemrnt5tt+tth+=l)) p00@e

**Comment by jd1378** [comment]
This shouldn't be an issue any longer
