### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by vasilyvaganov** [jd1378/otphelper#129]
Is it possible to make the name of the application in Russian not "Копирование SMS кода", but "OTP Helper"?

**Comment by vasilyvaganov** [comment]
Or make it so: if the application is in English, the name is also in English. Because now, if the system is in Russian and the app is in English, the name of the app will still be in Russian. I don't like this, because it makes it harder to find the app in the app search.

**Comment by jd1378** [comment]
well, even the name of the app in English is Copy SMS Code when installed, so even in English it does not contain "OTP" and not "Helper"

I know this sounds inconvenient, but I can't help it. name was intended as a kind of SEO boosting, and the app's name must match store listing because that's the correct expectation 

the OTP helper part is omitted because the application should not be that long

I'm sorry but I do not want to make this change.

tip: search for SMS, I assume you don't have 10 SMS apps, so it will be like in the top 3 results of your search
