### ISSUE TITLE
Create Weblate/Crowdin account for translating

### ISSUE THREAD

**Issue by inson1** [jd1378/otphelper#15]
I think it would be easier than do translations in code and then creating PR

**Comment by jd1378** [comment]
Its a good idea for translations,
But It require some work to set it up and I can't do it right now
But I leave this open so I'll try to do it at a later time

**Comment by pataquets** [comment]
Cross-linking to locked issue #10 to make readers there aware of this.
No pressure on ETA, but just trying to prevent anyone contributing via the wrong method and wasting their time. Although a backlink as a comment there would be more visible.
Since as of now, the Weblate project shows a "testing period" banner, I assume PR method is currently the working one, until Weblate is put into "production".

**Comment by jd1378** [comment]
Hey
weblate currently works if you contribute there, and I have asked for libre projects approval
I just had forgotten to close that issue, sorry

**Comment by pataquets** [comment]
Dropping the link here for those getting to this issue:
[Copy SMS Code - OTP Helper @ Hosted Weblate](https://hosted.weblate.org/projects/copy-sms-code-otp-helper/)
@inson1: care to close the issue?
