### ISSUE TITLE
Sometimes grabs SMS sender

### ISSUE THREAD

**Issue by JuliettaExpress** [jd1378/otphelper#33]
Occasionally the sender's number will be copied instead of the One-Time Passcode. For example these two from FedEx today:

> FedEx: Verification code 228193 expires in 10 minutes. Do not share it with anyone.

> FedEx: Authorization code 153317 expires in 10 minutes. If you didn't request the code, call 1.800.463.3339. Reply Stop to cancel. Msg&data rates may apply.

It instead copies `25161`, which is the number that sent those two texts. Might have to do with the sender number being shorter maybe? Haven't seen it copy a full 9-digit number yet.

**Comment by jd1378** [comment]
hmm, this might have to do with the notification title being appended to the body in case the notification title has the code
I guess it was a wrong decision, since only a few contain code in the title from what I have seen, and many sms apps include phone number instead, which it's causing it to capture the wrong code I guess

I'll fix this behavior

**Comment by jd1378** [comment]
released in [1.7.0](https://github.com/jd1378/otphelper/releases/tag/v1.7.0), let me know if the issue persists.

**Comment by Naomitr0n** [comment]
Still happens with 1.7.1. F-droid doesn't have 1.8.0 yet, not sure if it would be resolved there.

Don't know if this is relevant, but I do use Truecaller which has its own "smart notification" system that notifies on things like one-time passcodes and includes sender info within the body of the notification. Are you reading directly from texts received or from notifications? If you're reading from notifications, I imagine adding whitelist filtering based on which apps are sending the notification would be ideal as I use Textra as my default texting app.

**Comment by jd1378** [comment]
when you press ignore on detected code notification it ignores all notifications from that app , so I think it should help you already
 The app is reading notifications text

**Comment by Naomitr0n** [comment]
Looks like it's reading the OTP as the title and the sender as the body for some reason:

![Screenshot_20231125-125939](https://github.com/jd1378/otphelper/assets/81192719/492fe6ab-52d6-4046-a7e3-3c415e9e9fe0)

I can't tell if it's detecting the FedEx OTP format either. I'm not sure I've seen it copy two OTP's at the same time for me to know if it sees the FedEx one from Textra or just Truecaller displaying it. Or at least, I don't see anything telling me it's reading multiple -- I only see the one notification per event in my phone's Notification History and no in-app detection history in otphelper so it's hard for me to say if it's potentially not recognizing the code in Textra but is in Truecaller and only grabs the first one it recognizes per event or what's going on.

I thought it might have to do with the sender number being five digits, but I deleted the entry from the screenshot above before testing the My Social Security site (ssa.gov) and that one's working just fine:

![Screenshot_20231125-130400](https://github.com/jd1378/otphelper/assets/81192719/c64fbe26-ac31-480f-9a62-57927203d195)

I don't know that my LG V60's Notification History is being fully honest with the exact order either when they all hit at once, unless maybe it goes by order dismissed rather than order generated:

![Screenshot_20231125-131940](https://github.com/jd1378/otphelper/assets/81192719/800b38a0-7142-4aeb-a1f8-253e55a82914)

It's not immediately obvious to me how the ignore list in otphelper is filtered, is it based on notification title or sending app? I don't know if it's ignoring *all* of Truecaller notifications or if it's specifically ones with a certain title -- if it's from a certain title then it's definitely not gonna work given it's reading the OTP itself as the title

**Comment by jd1378** [comment]
ahh my bad, really sorry
the ignore behavior change (to app id) was added in 1.8.0
please wait a bit till it's released on f-droid and test again after it by ignoring again, or you can directly download the latest version from github and update the app, as both have the same signature

**Comment by Naomitr0n** [comment]
Ignoring Truecaller now has otphelper seeing FedEx codes thru Textra :+1:

What about adding toggleable otp logging that shows detected codes and what app sends them etc.? I remember a bug in an older version where every F-Droid update was detected, would be great to enable logging for a bit and add apps to ignore as needed from that -- plus keep track of what's actually being detected in case there's a use case that isn't being caught correctly or that isn't caught at all.

**Comment by jd1378** [comment]
That's a really interesting and good idea and I would like to implement it when I have time, but sadly I'm very busy at the moment
