### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Samyak-Bumb** [jd1378/otphelper#37]
Hey man just wanted to ask you which resources you used to learn kotlin & which videos will you refer to watch

**Comment by jd1378** [comment]
For kotlin I don't remember using a specific resource, because I already knew many other languages, i just needed to learn the syntax

For jetpack compose though, i highly recommend reading the android docs completely, they are very good, and then i suggest looking at the sample projects they host on github, they are very helpful
