### ISSUE TITLE
Unable to detect HDFC Bank OTPs

### ISSUE THREAD

**Issue by adarsh1001** [jd1378/otphelper#7]
First off, thanks for creating and maintaining this app! I always wanted a simple offline OTP parser and this is a first.

HDFC is a major bank in India and for one of their logins, they send this SMS:

_844556 is the One Time Password (OTP) to 2FA Login of your HDFC securities trading and investment account._

The OTP in this isn't detected, despite the message having the word "OTP" as well as its full form. Maybe the parser is having an issue due to brackets around "OTP"?

**Comment by jd1378** [comment]
Hi
thanks for reporting this

the issue was that "2" in "2FA" was throwing off the regex
it got fixed by adding 2FA as a sensitive word

I also improved the code matcher by limiting it to at least 4 characters

while doing this, I found a case of [Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html) and fixed it, which should improve the performance of the regex as well

will release this with 1.3.0 after merging some more translations
