### ISSUE TITLE
Feature request: able to manually add keywords to parse

### ISSUE THREAD

**Issue by tomatojam42** [jd1378/otphelper#9]
Hello.
Well, all is in the title of issue.

I receive sms in russian and without any special tags like <#>.
Just `ваш код: 654321`
Also may be `код подтверждения`, `код доступа` and so on.
And **otphelper** not parse it.

Such ways to deal with it:

1. Every not-English-speaking guy, who wants to use otphelper, creates his own wordlist or/and algoritm right inside an app.
   1.1. And if we are all kindful people, then we have to share the wordlist for improving the tool.

2. I may to collect my sms, analyse and create algorithms, like so for English or Arabian if any.

Or app is running simply as (WATCH PATTERN <#>) ?

**Comment by jd1378** [comment]
I've added `код` in [v1.3.0](https://github.com/jd1378/otphelper/releases/tag/v1.3.0)
please open another issue if you need other words to be added as well

**Comment by jd1378** [comment]
Hi @nvllz 
I'm somewhat against the idea personally, due to reasons I pointed out above, but the main reason is I don't have the time to add new features

Either the project needs to have financial support for me to put more time on it, or have contributors help me in adding features or improving the app
Otherwise It usually takes my free times to develop the features

**Comment by jd1378** [comment]
I understand and I try to implement the feature, just that it may take a while
thanks for the feedback :)

**Comment by pataquets** [comment]
First and foremost, I'm using the app and it's great. So nifty and useful!
Thank you very much for sharing your effort in crafting such a fine piece of software.

Just because of its usefulness, just dropping another solution to a problem stated above.
(Once|if) the app grows enough in user base, consider moving it into a Github organization, in case sometime in the future you fancy from adding collaborators to even handing off the app completely.
Not necessarily now, just pointing out the alternate solution to changes in your availability/commitment/interest/whatever-you-feel-like.

**Comment by sbellon** [comment]
I also second the idea of having per-user configurable keywords. While the idea of having it hard-coded "for the benefit of all" sounds charming at first, there is no "one size fits all" solution and you will not be able to please everyone.

E.g. in your static list, there already is `Einmalkennwort` but `Kennwort` is missing. I could directly see that also something like `Einmalpasswort`, `Passwort` and `Password` may be useful. If users can configure this for their own usage, they can fine-tune it for the apps they use, not get false positive notifications and you remove the maintenance effort from your app.

**Comment by jd1378** [comment]
Hi
I wanted to wait a bit before announcing it, since there's still much to do, 
But I'm working on it and the feature plus history of detection (+ highlighting what caused detection and what was detected) will be added in the coming weeks

Thanks for helping improve the app with your suggestions

**Comment by pataquets** [comment]
That's great, @jd1378! Thank you.
I'd like to point out that some "copy detection string expression/regex/whatever" kind of feature would help those wanting to contribute back their custom detection strings, once they have fine-tuned themselves. Sure, it's not a killer feature nor deal breaker, but worth sharing 2c here at least, IMHO.

**Comment by jd1378** [comment]
Good idea, sounds useful for testing for example on regex101.com

**Comment by jd1378** [comment]
Hi
a release candidate was released:
https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc

please try and let me know if you have any issues

**Comment by jd1378** [comment]
Hey,
I have released [v1.16.0-rc2](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc2) which resolves some of the issues and adds more features
please try it when you have time

**Comment by jd1378** [comment]
sorry for the notifications
I have released [v1.16.0-rc4](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc4)
which contains some important fixes for reliability of the app (if you had issues with app not working after some time and reopening it did not help)

**Comment by sbellon** [comment]
I have added new keywords and removed default ones. Works fine for me so far. :+1:

**Comment by jd1378** [comment]
[v1.16.0](https://github.com/jd1378/otphelper/releases/tag/v1.16.0) has been released

Thank you everyone!
