### ISSUE TITLE
o2/Telefonica Germany not detected correctly 

### ISSUE THREAD

**Issue by SysCrasher** [jd1378/otphelper#92]
2fa Codes from O2 (Telefonica) Germany are not recognized correctly (Maybe because this kind of special snowflake text formatting).

Text:
`Guten Tag,
um Ihre Identität zu bestätigen, geben Sie bitte unter login.o2online.de folgenden o2 Sicherheitscode ein:
BITTE NIEMALS AM TELEFON VORLESEN ODER IN EINEM CHAT WEITERGEBEN!

858823

Falls Sie diesen Vorgang nicht selbst veranlasst haben, wenden Sie sich bitte umgehend an den o2 Kundenservice, um einen Identitätsdiebstahl auszuschließen und ändern Sie Ihr aktuelles Kennwort.
Informationen dazu finden Sie unter https://www.o2online.de/service/sicherheit/
Ihr o2 Team
@login.o2online.de #858823`

It detects the word "BITTE" instead of the number (in this SMS 858823). The number is mentioned twice in the text message. One time in the normal way, the second time at the end of the message with an #.

I don't know if you want to look into it, if not close this thread.

**Comment by jd1378** [comment]
I have look into it, wrote test, tried some stuff, sadly I don't think I can do anything about it,
mostly because of the `:` character
nearly all of the SMS messages so far always put the code immediately after the : character, which makes it hard to detect when it's not immediately after : 
you might think the only number after colon is the code, so why not easy? because the app handles codes that contain alphabets as well
I tried to contact the website to send them a suggestion (always worth a try), but could not find an email address or connect to the online chat, or even open the feedback form for the website
